language: scala
sudo: true
scala:
- 2.11.8
jdk:
- oraclejdk8
install: true
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
script:
- cd $TRAVIS_BUILD_DIR
- travis_retry sbt --warn ++$TRAVIS_SCALA_VERSION compile
- sbt ++$TRAVIS_SCALA_VERSION test
- sbt --warn ++$TRAVIS_SCALA_VERSION publish-local
notifications:
  email: false
env:
  global:
    # TODO
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { cd $TRAVIS_BUILD_DIR && sbt --info ++$TRAVIS_SCALA_VERSION -Dtravis=1 publish; };'
